/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttendanceId = bigint;
export interface AttendanceRecord {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'memberId' : MemberId,
  'markedAt' : Timestamp,
  'meetingId' : MeetingId,
}
export interface AttendanceReportMemberDetail {
  'status' : AttendanceStatus,
  'memberId' : MemberId,
  'memberName' : string,
}
export interface AttendanceReportRow {
  'memberDetails' : Array<AttendanceReportMemberDetail>,
  'meetingDate' : Timestamp,
  'chapterId' : ChapterId,
  'meetingTitle' : string,
  'totalAttendees' : bigint,
  'attendanceRate' : number,
  'absentCount' : bigint,
  'meetingId' : MeetingId,
  'chapterName' : string,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export interface Chapter {
  'id' : ChapterId,
  'name' : string,
  'description' : string,
}
export type ChapterId = bigint;
export interface DashboardStats {
  'memberCount' : bigint,
  'referralCount' : bigint,
  'messageCount' : bigint,
  'meetingCount' : bigint,
  'chapterCount' : bigint,
}
export type DealStatus = { 'closed' : null } |
  { 'pending' : null } |
  { 'in_progress' : null };
export interface ImportResult {
  'imported' : bigint,
  'skipped' : bigint,
  'errors' : Array<string>,
}
export interface LeaderboardEntry {
  'memberId' : MemberId,
  'businessName' : string,
  'chapterId' : ChapterId,
  'referralCount' : bigint,
  'memberName' : string,
}
export interface Meeting {
  'id' : MeetingId,
  'title' : string,
  'date' : Timestamp,
  'description' : string,
  'chapterId' : ChapterId,
  'location' : string,
}
export type MeetingId = bigint;
export interface Member {
  'id' : MemberId,
  'businessCategory' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'businessName' : string,
  'chapterId' : ChapterId,
  'isActive' : boolean,
  'email' : string,
  'website' : string,
  'phone' : string,
}
export type MemberId = bigint;
export interface MemberImport {
  'businessCategory' : string,
  'name' : string,
  'businessName' : string,
  'chapterId' : ChapterId,
  'email' : string,
  'website' : string,
  'phone' : string,
}
export interface Message {
  'id' : MessageId,
  'subject' : string,
  'body' : string,
  'chapterId' : [] | [ChapterId],
  'sentAt' : Timestamp,
  'recipientCount' : bigint,
}
export type MessageId = bigint;
export interface Referral {
  'id' : ReferralId,
  'businessCategory' : string,
  'createdAt' : Timestamp,
  'receiverId' : MemberId,
  'notes' : string,
  'dealValue' : [] | [bigint],
  'dealStatus' : DealStatus,
  'giverId' : MemberId,
}
export type ReferralId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'addMeeting' : ActorMethod<
    [string, ChapterId, Timestamp, string, string],
    Meeting
  >,
  'addMember' : ActorMethod<
    [string, string, string, string, string, string, ChapterId],
    Member
  >,
  'addReferral' : ActorMethod<
    [MemberId, MemberId, string, DealStatus, [] | [bigint], string],
    Referral
  >,
  'deleteMeeting' : ActorMethod<[MeetingId], boolean>,
  'deleteMember' : ActorMethod<[MemberId], boolean>,
  'deleteReferral' : ActorMethod<[ReferralId], boolean>,
  'getAllReferrals' : ActorMethod<[], Array<Referral>>,
  'getAttendanceByMeeting' : ActorMethod<[MeetingId], Array<AttendanceRecord>>,
  'getAttendanceByMember' : ActorMethod<[MemberId], Array<AttendanceRecord>>,
  'getAttendanceReport' : ActorMethod<
    [[] | [ChapterId], [] | [Timestamp], [] | [Timestamp]],
    Array<AttendanceReportRow>
  >,
  'getChapter' : ActorMethod<[ChapterId], [] | [Chapter]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getLeaderboard' : ActorMethod<[[] | [ChapterId]], Array<LeaderboardEntry>>,
  'getMeeting' : ActorMethod<[MeetingId], [] | [Meeting]>,
  'getMember' : ActorMethod<[MemberId], [] | [Member]>,
  'getMessage' : ActorMethod<[MessageId], [] | [Message]>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getReferralsByGiver' : ActorMethod<[MemberId], Array<Referral>>,
  'getReferralsByReceiver' : ActorMethod<[MemberId], Array<Referral>>,
  'importMembers' : ActorMethod<[Array<MemberImport>], ImportResult>,
  'listChapters' : ActorMethod<[], Array<Chapter>>,
  'listMeetings' : ActorMethod<[], Array<Meeting>>,
  'listMeetingsByChapter' : ActorMethod<[ChapterId], Array<Meeting>>,
  'listMembers' : ActorMethod<[], Array<Member>>,
  'listMembersByChapter' : ActorMethod<[ChapterId], Array<Member>>,
  'markAttendance' : ActorMethod<
    [MeetingId, MemberId, AttendanceStatus],
    AttendanceRecord
  >,
  'sendMessage' : ActorMethod<[string, string, [] | [ChapterId]], Message>,
  'updateAttendance' : ActorMethod<
    [AttendanceId, AttendanceStatus],
    [] | [AttendanceRecord]
  >,
  'updateMeeting' : ActorMethod<
    [MeetingId, string, ChapterId, Timestamp, string, string],
    [] | [Meeting]
  >,
  'updateMember' : ActorMethod<
    [
      MemberId,
      string,
      string,
      string,
      string,
      string,
      string,
      ChapterId,
      boolean,
    ],
    [] | [Member]
  >,
  'updateReferral' : ActorMethod<
    [ReferralId, string, DealStatus, [] | [bigint], string],
    [] | [Referral]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];