/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChapterId = IDL.Nat;
export const Timestamp = IDL.Int;
export const MeetingId = IDL.Nat;
export const Meeting = IDL.Record({
  'id' : MeetingId,
  'title' : IDL.Text,
  'date' : Timestamp,
  'description' : IDL.Text,
  'chapterId' : ChapterId,
  'location' : IDL.Text,
});
export const MemberId = IDL.Nat;
export const Member = IDL.Record({
  'id' : MemberId,
  'businessCategory' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'businessName' : IDL.Text,
  'chapterId' : ChapterId,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'phone' : IDL.Text,
});
export const DealStatus = IDL.Variant({
  'closed' : IDL.Null,
  'pending' : IDL.Null,
  'in_progress' : IDL.Null,
});
export const ReferralId = IDL.Nat;
export const Referral = IDL.Record({
  'id' : ReferralId,
  'businessCategory' : IDL.Text,
  'createdAt' : Timestamp,
  'receiverId' : MemberId,
  'notes' : IDL.Text,
  'dealValue' : IDL.Opt(IDL.Nat),
  'dealStatus' : DealStatus,
  'giverId' : MemberId,
});
export const AttendanceId = IDL.Nat;
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'memberId' : MemberId,
  'markedAt' : Timestamp,
  'meetingId' : MeetingId,
});
export const AttendanceReportMemberDetail = IDL.Record({
  'status' : AttendanceStatus,
  'memberId' : MemberId,
  'memberName' : IDL.Text,
});
export const AttendanceReportRow = IDL.Record({
  'memberDetails' : IDL.Vec(AttendanceReportMemberDetail),
  'meetingDate' : Timestamp,
  'chapterId' : ChapterId,
  'meetingTitle' : IDL.Text,
  'totalAttendees' : IDL.Nat,
  'attendanceRate' : IDL.Float64,
  'absentCount' : IDL.Nat,
  'meetingId' : MeetingId,
  'chapterName' : IDL.Text,
});
export const Chapter = IDL.Record({
  'id' : ChapterId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'memberCount' : IDL.Nat,
  'referralCount' : IDL.Nat,
  'messageCount' : IDL.Nat,
  'meetingCount' : IDL.Nat,
  'chapterCount' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'memberId' : MemberId,
  'businessName' : IDL.Text,
  'chapterId' : ChapterId,
  'referralCount' : IDL.Nat,
  'memberName' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'chapterId' : IDL.Opt(ChapterId),
  'sentAt' : Timestamp,
  'recipientCount' : IDL.Nat,
});
export const MemberImport = IDL.Record({
  'businessCategory' : IDL.Text,
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'chapterId' : ChapterId,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'phone' : IDL.Text,
});
export const ImportResult = IDL.Record({
  'imported' : IDL.Nat,
  'skipped' : IDL.Nat,
  'errors' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addMeeting' : IDL.Func(
      [IDL.Text, ChapterId, Timestamp, IDL.Text, IDL.Text],
      [Meeting],
      [],
    ),
  'addMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ChapterId],
      [Member],
      [],
    ),
  'addReferral' : IDL.Func(
      [MemberId, MemberId, IDL.Text, DealStatus, IDL.Opt(IDL.Nat), IDL.Text],
      [Referral],
      [],
    ),
  'deleteMeeting' : IDL.Func([MeetingId], [IDL.Bool], []),
  'deleteMember' : IDL.Func([MemberId], [IDL.Bool], []),
  'deleteReferral' : IDL.Func([ReferralId], [IDL.Bool], []),
  'getAllReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
  'getAttendanceByMeeting' : IDL.Func(
      [MeetingId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByMember' : IDL.Func(
      [MemberId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceReport' : IDL.Func(
      [IDL.Opt(ChapterId), IDL.Opt(Timestamp), IDL.Opt(Timestamp)],
      [IDL.Vec(AttendanceReportRow)],
      ['query'],
    ),
  'getChapter' : IDL.Func([ChapterId], [IDL.Opt(Chapter)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Opt(ChapterId)],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMeeting' : IDL.Func([MeetingId], [IDL.Opt(Meeting)], ['query']),
  'getMember' : IDL.Func([MemberId], [IDL.Opt(Member)], ['query']),
  'getMessage' : IDL.Func([MessageId], [IDL.Opt(Message)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getReferralsByGiver' : IDL.Func([MemberId], [IDL.Vec(Referral)], ['query']),
  'getReferralsByReceiver' : IDL.Func(
      [MemberId],
      [IDL.Vec(Referral)],
      ['query'],
    ),
  'importMembers' : IDL.Func([IDL.Vec(MemberImport)], [ImportResult], []),
  'listChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'listMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
  'listMeetingsByChapter' : IDL.Func(
      [ChapterId],
      [IDL.Vec(Meeting)],
      ['query'],
    ),
  'listMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'listMembersByChapter' : IDL.Func([ChapterId], [IDL.Vec(Member)], ['query']),
  'markAttendance' : IDL.Func(
      [MeetingId, MemberId, AttendanceStatus],
      [AttendanceRecord],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ChapterId)],
      [Message],
      [],
    ),
  'updateAttendance' : IDL.Func(
      [AttendanceId, AttendanceStatus],
      [IDL.Opt(AttendanceRecord)],
      [],
    ),
  'updateMeeting' : IDL.Func(
      [MeetingId, IDL.Text, ChapterId, Timestamp, IDL.Text, IDL.Text],
      [IDL.Opt(Meeting)],
      [],
    ),
  'updateMember' : IDL.Func(
      [
        MemberId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ChapterId,
        IDL.Bool,
      ],
      [IDL.Opt(Member)],
      [],
    ),
  'updateReferral' : IDL.Func(
      [ReferralId, IDL.Text, DealStatus, IDL.Opt(IDL.Nat), IDL.Text],
      [IDL.Opt(Referral)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChapterId = IDL.Nat;
  const Timestamp = IDL.Int;
  const MeetingId = IDL.Nat;
  const Meeting = IDL.Record({
    'id' : MeetingId,
    'title' : IDL.Text,
    'date' : Timestamp,
    'description' : IDL.Text,
    'chapterId' : ChapterId,
    'location' : IDL.Text,
  });
  const MemberId = IDL.Nat;
  const Member = IDL.Record({
    'id' : MemberId,
    'businessCategory' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'businessName' : IDL.Text,
    'chapterId' : ChapterId,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DealStatus = IDL.Variant({
    'closed' : IDL.Null,
    'pending' : IDL.Null,
    'in_progress' : IDL.Null,
  });
  const ReferralId = IDL.Nat;
  const Referral = IDL.Record({
    'id' : ReferralId,
    'businessCategory' : IDL.Text,
    'createdAt' : Timestamp,
    'receiverId' : MemberId,
    'notes' : IDL.Text,
    'dealValue' : IDL.Opt(IDL.Nat),
    'dealStatus' : DealStatus,
    'giverId' : MemberId,
  });
  const AttendanceId = IDL.Nat;
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'memberId' : MemberId,
    'markedAt' : Timestamp,
    'meetingId' : MeetingId,
  });
  const AttendanceReportMemberDetail = IDL.Record({
    'status' : AttendanceStatus,
    'memberId' : MemberId,
    'memberName' : IDL.Text,
  });
  const AttendanceReportRow = IDL.Record({
    'memberDetails' : IDL.Vec(AttendanceReportMemberDetail),
    'meetingDate' : Timestamp,
    'chapterId' : ChapterId,
    'meetingTitle' : IDL.Text,
    'totalAttendees' : IDL.Nat,
    'attendanceRate' : IDL.Float64,
    'absentCount' : IDL.Nat,
    'meetingId' : MeetingId,
    'chapterName' : IDL.Text,
  });
  const Chapter = IDL.Record({
    'id' : ChapterId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'memberCount' : IDL.Nat,
    'referralCount' : IDL.Nat,
    'messageCount' : IDL.Nat,
    'meetingCount' : IDL.Nat,
    'chapterCount' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'memberId' : MemberId,
    'businessName' : IDL.Text,
    'chapterId' : ChapterId,
    'referralCount' : IDL.Nat,
    'memberName' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'chapterId' : IDL.Opt(ChapterId),
    'sentAt' : Timestamp,
    'recipientCount' : IDL.Nat,
  });
  const MemberImport = IDL.Record({
    'businessCategory' : IDL.Text,
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'chapterId' : ChapterId,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ImportResult = IDL.Record({
    'imported' : IDL.Nat,
    'skipped' : IDL.Nat,
    'errors' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addMeeting' : IDL.Func(
        [IDL.Text, ChapterId, Timestamp, IDL.Text, IDL.Text],
        [Meeting],
        [],
      ),
    'addMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ChapterId],
        [Member],
        [],
      ),
    'addReferral' : IDL.Func(
        [MemberId, MemberId, IDL.Text, DealStatus, IDL.Opt(IDL.Nat), IDL.Text],
        [Referral],
        [],
      ),
    'deleteMeeting' : IDL.Func([MeetingId], [IDL.Bool], []),
    'deleteMember' : IDL.Func([MemberId], [IDL.Bool], []),
    'deleteReferral' : IDL.Func([ReferralId], [IDL.Bool], []),
    'getAllReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
    'getAttendanceByMeeting' : IDL.Func(
        [MeetingId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByMember' : IDL.Func(
        [MemberId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceReport' : IDL.Func(
        [IDL.Opt(ChapterId), IDL.Opt(Timestamp), IDL.Opt(Timestamp)],
        [IDL.Vec(AttendanceReportRow)],
        ['query'],
      ),
    'getChapter' : IDL.Func([ChapterId], [IDL.Opt(Chapter)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Opt(ChapterId)],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMeeting' : IDL.Func([MeetingId], [IDL.Opt(Meeting)], ['query']),
    'getMember' : IDL.Func([MemberId], [IDL.Opt(Member)], ['query']),
    'getMessage' : IDL.Func([MessageId], [IDL.Opt(Message)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getReferralsByGiver' : IDL.Func(
        [MemberId],
        [IDL.Vec(Referral)],
        ['query'],
      ),
    'getReferralsByReceiver' : IDL.Func(
        [MemberId],
        [IDL.Vec(Referral)],
        ['query'],
      ),
    'importMembers' : IDL.Func([IDL.Vec(MemberImport)], [ImportResult], []),
    'listChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'listMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
    'listMeetingsByChapter' : IDL.Func(
        [ChapterId],
        [IDL.Vec(Meeting)],
        ['query'],
      ),
    'listMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'listMembersByChapter' : IDL.Func(
        [ChapterId],
        [IDL.Vec(Member)],
        ['query'],
      ),
    'markAttendance' : IDL.Func(
        [MeetingId, MemberId, AttendanceStatus],
        [AttendanceRecord],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ChapterId)],
        [Message],
        [],
      ),
    'updateAttendance' : IDL.Func(
        [AttendanceId, AttendanceStatus],
        [IDL.Opt(AttendanceRecord)],
        [],
      ),
    'updateMeeting' : IDL.Func(
        [MeetingId, IDL.Text, ChapterId, Timestamp, IDL.Text, IDL.Text],
        [IDL.Opt(Meeting)],
        [],
      ),
    'updateMember' : IDL.Func(
        [
          MemberId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ChapterId,
          IDL.Bool,
        ],
        [IDL.Opt(Member)],
        [],
      ),
    'updateReferral' : IDL.Func(
        [ReferralId, IDL.Text, DealStatus, IDL.Opt(IDL.Nat), IDL.Text],
        [IDL.Opt(Referral)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };