/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    memberId: MemberId;
    businessName: string;
    chapterId: ChapterId;
    referralCount: bigint;
    memberName: string;
}
export type Timestamp = bigint;
export interface Meeting {
    id: MeetingId;
    title: string;
    date: Timestamp;
    description: string;
    chapterId: ChapterId;
    location: string;
}
export type MemberId = bigint;
export interface ImportResult {
    imported: bigint;
    skipped: bigint;
    errors: Array<string>;
}
export type AttendanceId = bigint;
export interface MemberImport {
    businessCategory: string;
    name: string;
    businessName: string;
    chapterId: ChapterId;
    email: string;
    website: string;
    phone: string;
}
export interface DashboardStats {
    memberCount: bigint;
    referralCount: bigint;
    messageCount: bigint;
    meetingCount: bigint;
    chapterCount: bigint;
}
export type ChapterId = bigint;
export interface Chapter {
    id: ChapterId;
    name: string;
    description: string;
}
export type ReferralId = bigint;
export type MeetingId = bigint;
export interface AttendanceReportRow {
    memberDetails: Array<AttendanceReportMemberDetail>;
    meetingDate: Timestamp;
    chapterId: ChapterId;
    meetingTitle: string;
    totalAttendees: bigint;
    attendanceRate: number;
    absentCount: bigint;
    meetingId: MeetingId;
    chapterName: string;
}
export interface AttendanceReportMemberDetail {
    status: AttendanceStatus;
    memberId: MemberId;
    memberName: string;
}
export type MessageId = bigint;
export interface Referral {
    id: ReferralId;
    businessCategory: string;
    createdAt: Timestamp;
    receiverId: MemberId;
    notes: string;
    dealValue?: bigint;
    dealStatus: DealStatus;
    giverId: MemberId;
}
export interface Message {
    id: MessageId;
    subject: string;
    body: string;
    chapterId?: ChapterId;
    sentAt: Timestamp;
    recipientCount: bigint;
}
export interface Member {
    id: MemberId;
    businessCategory: string;
    name: string;
    createdAt: Timestamp;
    businessName: string;
    chapterId: ChapterId;
    isActive: boolean;
    email: string;
    website: string;
    phone: string;
}
export interface AttendanceRecord {
    id: AttendanceId;
    status: AttendanceStatus;
    memberId: MemberId;
    markedAt: Timestamp;
    meetingId: MeetingId;
}
export enum AttendanceStatus {
    present = "present",
    absent = "absent"
}
export enum DealStatus {
    closed = "closed",
    pending = "pending",
    in_progress = "in_progress"
}
export interface backendInterface {
    addMeeting(title: string, chapterId: ChapterId, date: Timestamp, location: string, description: string): Promise<Meeting>;
    addMember(name: string, businessName: string, businessCategory: string, email: string, phone: string, website: string, chapterId: ChapterId): Promise<Member>;
    addReferral(giverId: MemberId, receiverId: MemberId, businessCategory: string, dealStatus: DealStatus, dealValue: bigint | null, notes: string): Promise<Referral>;
    deleteMeeting(id: MeetingId): Promise<boolean>;
    deleteMember(id: MemberId): Promise<boolean>;
    deleteReferral(id: ReferralId): Promise<boolean>;
    getAllReferrals(): Promise<Array<Referral>>;
    getAttendanceByMeeting(meetingId: MeetingId): Promise<Array<AttendanceRecord>>;
    getAttendanceByMember(memberId: MemberId): Promise<Array<AttendanceRecord>>;
    getAttendanceReport(chapterId: ChapterId | null, fromDate: Timestamp | null, toDate: Timestamp | null): Promise<Array<AttendanceReportRow>>;
    getChapter(id: ChapterId): Promise<Chapter | null>;
    getDashboardStats(): Promise<DashboardStats>;
    getLeaderboard(chapterId: ChapterId | null): Promise<Array<LeaderboardEntry>>;
    getMeeting(id: MeetingId): Promise<Meeting | null>;
    getMember(id: MemberId): Promise<Member | null>;
    getMessage(id: MessageId): Promise<Message | null>;
    getMessages(): Promise<Array<Message>>;
    getReferralsByGiver(giverId: MemberId): Promise<Array<Referral>>;
    getReferralsByReceiver(receiverId: MemberId): Promise<Array<Referral>>;
    importMembers(members: Array<MemberImport>): Promise<ImportResult>;
    listChapters(): Promise<Array<Chapter>>;
    listMeetings(): Promise<Array<Meeting>>;
    listMeetingsByChapter(chapterId: ChapterId): Promise<Array<Meeting>>;
    listMembers(): Promise<Array<Member>>;
    listMembersByChapter(chapterId: ChapterId): Promise<Array<Member>>;
    markAttendance(meetingId: MeetingId, memberId: MemberId, status: AttendanceStatus): Promise<AttendanceRecord>;
    sendMessage(subject: string, body: string, chapterId: ChapterId | null): Promise<Message>;
    updateAttendance(id: AttendanceId, status: AttendanceStatus): Promise<AttendanceRecord | null>;
    updateMeeting(id: MeetingId, title: string, chapterId: ChapterId, date: Timestamp, location: string, description: string): Promise<Meeting | null>;
    updateMember(id: MemberId, name: string, businessName: string, businessCategory: string, email: string, phone: string, website: string, chapterId: ChapterId, isActive: boolean): Promise<Member | null>;
    updateReferral(id: ReferralId, businessCategory: string, dealStatus: DealStatus, dealValue: bigint | null, notes: string): Promise<Referral | null>;
}
import type { AttendanceId as _AttendanceId, AttendanceRecord as _AttendanceRecord, AttendanceReportMemberDetail as _AttendanceReportMemberDetail, AttendanceReportRow as _AttendanceReportRow, AttendanceStatus as _AttendanceStatus, Chapter as _Chapter, ChapterId as _ChapterId, DealStatus as _DealStatus, Meeting as _Meeting, MeetingId as _MeetingId, Member as _Member, MemberId as _MemberId, Message as _Message, MessageId as _MessageId, Referral as _Referral, ReferralId as _ReferralId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMeeting(arg0: string, arg1: ChapterId, arg2: Timestamp, arg3: string, arg4: string): Promise<Meeting> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeeting(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeeting(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addMember(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: ChapterId): Promise<Member> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addReferral(arg0: MemberId, arg1: MemberId, arg2: string, arg3: DealStatus, arg4: bigint | null, arg5: string): Promise<Referral> {
        if (this.processError) {
            try {
                const result = await this.actor.addReferral(arg0, arg1, arg2, to_candid_DealStatus_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Referral_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReferral(arg0, arg1, arg2, to_candid_DealStatus_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Referral_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMeeting(arg0: MeetingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeeting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeeting(arg0);
            return result;
        }
    }
    async deleteMember(arg0: MemberId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async deleteReferral(arg0: ReferralId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReferral(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReferral(arg0);
            return result;
        }
    }
    async getAllReferrals(): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReferrals();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReferrals();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByMeeting(arg0: MeetingId): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByMeeting(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByMeeting(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByMember(arg0: MemberId): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByMember(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByMember(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceReport(arg0: ChapterId | null, arg1: Timestamp | null, arg2: Timestamp | null): Promise<Array<AttendanceReportRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceReport(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceReport(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChapter(arg0: ChapterId): Promise<Chapter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapter(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapter(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLeaderboard(arg0: ChapterId | null): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMeeting(arg0: MeetingId): Promise<Meeting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeeting(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeeting(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMember(arg0: MemberId): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessage(arg0: MessageId): Promise<Message | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessage(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessage(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralsByGiver(arg0: MemberId): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralsByGiver(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralsByGiver(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralsByReceiver(arg0: MemberId): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralsByReceiver(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralsByReceiver(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async importMembers(arg0: Array<MemberImport>): Promise<ImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.importMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importMembers(arg0);
            return result;
        }
    }
    async listChapters(): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChapters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChapters();
            return result;
        }
    }
    async listMeetings(): Promise<Array<Meeting>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMeetings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMeetings();
            return result;
        }
    }
    async listMeetingsByChapter(arg0: ChapterId): Promise<Array<Meeting>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMeetingsByChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMeetingsByChapter(arg0);
            return result;
        }
    }
    async listMembers(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMembers();
            return result;
        }
    }
    async listMembersByChapter(arg0: ChapterId): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMembersByChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMembersByChapter(arg0);
            return result;
        }
    }
    async markAttendance(arg0: MeetingId, arg1: MemberId, arg2: AttendanceStatus): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, to_candid_AttendanceStatus_n31(this._uploadFile, this._downloadFile, arg2));
                return from_candid_AttendanceRecord_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, to_candid_AttendanceStatus_n31(this._uploadFile, this._downloadFile, arg2));
            return from_candid_AttendanceRecord_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: ChapterId | null): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Message_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Message_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAttendance(arg0: AttendanceId, arg1: AttendanceStatus): Promise<AttendanceRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAttendance(arg0, to_candid_AttendanceStatus_n31(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAttendance(arg0, to_candid_AttendanceStatus_n31(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMeeting(arg0: MeetingId, arg1: string, arg2: ChapterId, arg3: Timestamp, arg4: string, arg5: string): Promise<Meeting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMeeting(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMeeting(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMember(arg0: MemberId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: ChapterId, arg8: boolean): Promise<Member | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateReferral(arg0: ReferralId, arg1: string, arg2: DealStatus, arg3: bigint | null, arg4: string): Promise<Referral | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReferral(arg0, arg1, to_candid_DealStatus_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReferral(arg0, arg1, to_candid_DealStatus_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AttendanceRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceReportMemberDetail_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceReportMemberDetail): AttendanceReportMemberDetail {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceReportRow_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceReportRow): AttendanceReportRow {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DealStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DealStatus): DealStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Referral_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Referral): Referral {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Chapter]): Chapter | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Meeting]): Meeting | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Member]): Member | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : from_candid_Message_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChapterId]): ChapterId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceRecord]): AttendanceRecord | null {
    return value.length === 0 ? null : from_candid_AttendanceRecord_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Referral]): Referral | null {
    return value.length === 0 ? null : from_candid_Referral_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttendanceId;
    status: _AttendanceStatus;
    memberId: _MemberId;
    markedAt: _Timestamp;
    meetingId: _MeetingId;
}): {
    id: AttendanceId;
    status: AttendanceStatus;
    memberId: MemberId;
    markedAt: Timestamp;
    meetingId: MeetingId;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n13(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        markedAt: value.markedAt,
        meetingId: value.meetingId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberDetails: Array<_AttendanceReportMemberDetail>;
    meetingDate: _Timestamp;
    chapterId: _ChapterId;
    meetingTitle: string;
    totalAttendees: bigint;
    attendanceRate: number;
    absentCount: bigint;
    meetingId: _MeetingId;
    chapterName: string;
}): {
    memberDetails: Array<AttendanceReportMemberDetail>;
    meetingDate: Timestamp;
    chapterId: ChapterId;
    meetingTitle: string;
    totalAttendees: bigint;
    attendanceRate: number;
    absentCount: bigint;
    meetingId: MeetingId;
    chapterName: string;
} {
    return {
        memberDetails: from_candid_vec_n20(_uploadFile, _downloadFile, value.memberDetails),
        meetingDate: value.meetingDate,
        chapterId: value.chapterId,
        meetingTitle: value.meetingTitle,
        totalAttendees: value.totalAttendees,
        attendanceRate: value.attendanceRate,
        absentCount: value.absentCount,
        meetingId: value.meetingId,
        chapterName: value.chapterName
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AttendanceStatus;
    memberId: _MemberId;
    memberName: string;
}): {
    status: AttendanceStatus;
    memberId: MemberId;
    memberName: string;
} {
    return {
        status: from_candid_AttendanceStatus_n13(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        memberName: value.memberName
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    subject: string;
    body: string;
    chapterId: [] | [_ChapterId];
    sentAt: _Timestamp;
    recipientCount: bigint;
}): {
    id: MessageId;
    subject: string;
    body: string;
    chapterId?: ChapterId;
    sentAt: Timestamp;
    recipientCount: bigint;
} {
    return {
        id: value.id,
        subject: value.subject,
        body: value.body,
        chapterId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.chapterId)),
        sentAt: value.sentAt,
        recipientCount: value.recipientCount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReferralId;
    businessCategory: string;
    createdAt: _Timestamp;
    receiverId: _MemberId;
    notes: string;
    dealValue: [] | [bigint];
    dealStatus: _DealStatus;
    giverId: _MemberId;
}): {
    id: ReferralId;
    businessCategory: string;
    createdAt: Timestamp;
    receiverId: MemberId;
    notes: string;
    dealValue?: bigint;
    dealStatus: DealStatus;
    giverId: MemberId;
} {
    return {
        id: value.id,
        businessCategory: value.businessCategory,
        createdAt: value.createdAt,
        receiverId: value.receiverId,
        notes: value.notes,
        dealValue: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.dealValue)),
        dealStatus: from_candid_DealStatus_n7(_uploadFile, _downloadFile, value.dealStatus),
        giverId: value.giverId
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    pending: null;
} | {
    in_progress: null;
}): DealStatus {
    return "closed" in value ? DealStatus.closed : "pending" in value ? DealStatus.pending : "in_progress" in value ? DealStatus.in_progress : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceReportRow>): Array<AttendanceReportRow> {
    return value.map((x)=>from_candid_AttendanceReportRow_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceReportMemberDetail>): Array<AttendanceReportMemberDetail> {
    return value.map((x)=>from_candid_AttendanceReportMemberDetail_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Referral>): Array<Referral> {
    return value.map((x)=>from_candid_Referral_n4(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_DealStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStatus): _DealStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChapterId | null): [] | [_ChapterId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStatus): {
    closed: null;
} | {
    pending: null;
} | {
    in_progress: null;
} {
    return value == DealStatus.closed ? {
        closed: null
    } : value == DealStatus.pending ? {
        pending: null
    } : value == DealStatus.in_progress ? {
        in_progress: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
